"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <Jorge Nunez> and <Vivian Zhang>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: jn29423
UT EID 2: wz5363
"""

def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    string_len = len(string)
    string_lst = [[None] * string_len for _ in range(key)]
    j = 0
    i = 0
    k = 0
    l = 0
    encoded_str = ""
    while j <= string_len - 1:
        if i in (0,1):
            while i <= key - 1 and j <= string_len - 1:
                string_lst[i][j] = string[j]
                i += 1
                j += 1
        i -= 2
        if i == key - 2:
            while i >= 0 and j <= string_len - 1:
                string_lst[i][j] = string[j]
                i -= 1
                j += 1
        i += 2
    for k in range(key):
        for l in range(string_len):
            if string_lst[k][l] is not None:
                encoded_str += string_lst[k][l]
    return encoded_str

# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    string_len = len(string)
    string_lst = [[None] * string_len for val in range(key)]
    j = 0
    i = 0
    counter = 0
    decoded_str = ""
    while j <= string_len - 1:
        if i in (0,1):
            while i <= key - 1 and j <= string_len - 1:
                string_lst[i][j] = j
                i += 1
                j += 1
        i -= 2
        if i == key - 2:
            while i >= 0 and j <= string_len - 1:
                string_lst[i][j] = j
                i -= 1
                j += 1
        i += 2
    # Creates a 2D list with numbers in place of where letter should be
    for k in range(key):
        for l in range(string_len):
            if string_lst[k][l] is not None:
                string_lst[k][l] = string[counter]
                counter += 1
    # Should have encoded list, now just read through list
    # Re-establish loop variables
    j = 0
    i = 0
    while j <= string_len - 1:
        if i in (0,1):
            while i <= key - 1 and j <= string_len - 1:
                decoded_str += string_lst[i][j]
                i += 1
                j += 1
        i -= 2
        if i == key - 2:
            while i >= 0 and j <= string_len - 1:
                decoded_str += string_lst[i][j]
                i -= 1
                j += 1
        i += 2
    return decoded_str

# TODO: implement this function. You may delete this comment after you are done.
def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    new_string = ""
    string = string.lower()
    for elem in string:
        if elem.isalpha():
            new_string += elem
    return new_string

# TODO: implement this function. You may delete this comment after you are done.
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    # convert p and s into ASCII values. "a" starts at 97 and "z" ends at 122
    p_num = ord(p)
    s_num = ord(s)
    # get the encoded value
    encoded_char = (p_num + s_num) - 97
    if encoded_char > 122: # goes over the bounds
        encoded_char -= 26
    # turn it back into its letter value
    encoded_char = chr(encoded_char)

    return encoded_char



# TODO: implement this function. You may delete this comment after you are done.
def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    # convert p and s into ASCII values. "a" starts at 97 and "z" ends at 122
    num_p = ord(p)
    num_s = ord(s)
    # turn the encoded letter back to the plain text
    plain_char = (num_s - num_p) + 97
    if plain_char < 97:
        plain_char += 26
    # turn it back into its letter value
    plain_char = chr(plain_char)

    return plain_char

# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    encoded_phrase = ""
    passphrase = ""
    string = filter_string(string)
    str_len = len(string)
    phr_len = len(phrase)
    # Generates passphrase which repeats until len(phrase) = len(string)
    for i in range(str_len):
        count = 0
        for _ in range(phr_len):
            passphrase += phrase[count]
            count += 1
            i += 1
    for l in range(str_len):
        encoded_phrase += encode_character(passphrase[l], string[l])
    return encoded_phrase

    # passphrase is repeated to match the length of the string

# TODO: implement this function. You may delete this comment after you are done.
def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    decoded_phrase = ""
    passphrase = ""
    string = filter_string(string)
    str_len = len(string)
    phr_len = len(phrase)
    # Generates passphrase which repeats until len(phrase) = len(string)
    for i in range(str_len):
        count = 0
        for _ in range(phr_len):
            if len(passphrase) < len(string):
                passphrase += phrase[count]
                count += 1
                i += 1
    for l in range(str_len):
        decoded_phrase += decode_character(passphrase[l], string[l])
    return decoded_phrase


# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""

    # read the plain text from stdin (terminal/input)
    plain_text = input()

    # read the key from stdin (terminal/input)
    key = int(input())

    # encrypt and print the encoded text using rail fence cipher
    encoded_text = rail_fence_encode(plain_text, key)
    print("Rail Fence Cipher")
    print("")
    print(f"Plain Text: {plain_text}")
    print(f"Key: {key}")
    print(f"Encoded Text: {encoded_text}")

    # read encoded text from stdin (terminal/input)
    encoded_text = input()

    # read the key from stdin (terminal/input)
    key = int(input())
    print("")

    # decrypt and print the plain text using rail fence cipher
    decoded_text = rail_fence_decode(encoded_text, key)
    print(f"Encoded Text: {encoded_text}")
    print(f"Enter Key: {key}")
    print(f"Decoded Text: {decoded_text}")
    print("")
    # read the plain text from stdin (terminal/input)
    plain_text = input()
    # read the pass phrase from stdin (terminal/input)
    pass_phrase = input()
    # encrypt and print the encoded text using Vigenere cipher
    encoded_text = vigenere_encode(plain_text, pass_phrase)
    print("Vigenere Cipher")
    print("")
    print(f"Plain Text: {plain_text}")
    print(f"Pass Phrase: {pass_phrase}")
    print(f"Encoded Text: {encoded_text}")
    print("")
    # read the encoded text from stdin (terminal/input)
    encoded_text = input()
    # read the pass phrase from stdin (terminal/input)
    pass_phrase = input()
    # decrypt and print the plain text using Vigenere cipher
    decoded_text = vigenere_decode(encoded_text, pass_phrase)
    print(f"Encoded Text: {encoded_text}")
    print(f"Pass Phrase: {pass_phrase}")
    print(f"Decoded Text: {decoded_text}")

# Do NOT modify the following code.
if __name__ == "__main__":
    main()
